# Generated by Django 4.2.8 on 2024-06-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_cliente_created_cliente_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
    ]
