# Generated by Django 4.2.8 on 2024-06-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='fecha',
            field=models.DateField(),
        ),
    ]
