# Generated by Django 4.2.8 on 2024-06-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='imagen',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
