# Generated by Django 4.2.8 on 2024-07-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_categoria_tienda_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
